### ISSUE TITLE
Rated malicious by Bitdefender

### ISSUE THREAD

**Issue by raphpitt** [n00mkrad/flowframes#22]
Rated malicious by Bitdefender (in french):

![image](https://user-images.githubusercontent.com/34160362/107852298-4d479100-6e10-11eb-9252-f23fb91e8b4d.png)

**Comment by richardletshacks** [comment]
It's safe to use.
The false-positive detection will most likely be due to it running python scripts that could potentially harm your computer (but won't! there's no malicious code in these scripts).
On Flowframes side, there's not really anything you could do about that afaik. You will have to exclude it from BitDefender.

**Comment by n00mkrad** [comment]
I can't really provide support for these cases.

It's open-source and safe, I can't do anything against AV programs detecting it as a false positive. Just whitelist it in that case.

**Comment by raphpitt** [comment]
Yes, this is a false positive. This is only to notify that Bitdefender is now blocking (I haven't seen this mention anywhere about the project). Of course, I excluded the FF from the filter.

**Comment by Tsubajashi** [comment]
i suppose its hard to mark it "clean" as its I/O operations can be considered harmful.
the best way is to use a better AV which isnt detecting it as fast as a false positive - i personally use sophos home. its cheaper and more robust in my eyes.
