### ISSUE TITLE
Can flowframes be run with command line arguments?

### ISSUE THREAD

**Issue by creinemann** [n00mkrad/flowframes#67]
Could flowframes be run with a command line argument? For instance:

flowframes.exe video.mp4 then arguments for interpolation settings?

**Comment by n00mkrad** [comment]
Currently not

**Comment by creinemann** [comment]
Ok thanks, I am using Flowframes with Geostationary Satellite imagery, the results are very impressive!

**Comment by n00mkrad** [comment]
It's now possible on the latest code / patreon releases.

**Flowframes CLI Arguments:**

`<filepath>` - Simply add one or more (batch queue) file paths to the command (without `<>` or `-`)
`-start` - Auto-starts interpolation if files were specified
`-quit-when-done` - Auto-quits the app after processing has finished
`-factor` - Specify interpolation factor. 2/4/8 is valid. Example: `-factor=4`
`-ai` - Specify AI, otherwise last-used is used. Use the dropdown index (0 = First in dropdown)
`-output-mode` - Output mode. Same as above, use the dropdown index. 0 would be MP4, 1 MKV, etc
`-model` - Specify model. Same as above, uses dropdown index.

**Comment by creinemann** [comment]
Thanks!

**Comment by noobtoob4lyfe** [comment]
Can you give an example of a full command?  I'm trying "flowframes -filepath=X.mp4 -factor=4 -start" and all it's doing is opening the app.  Any ideas where I'm going wrong?
